AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - bin/bundle
    - bin/rake
    - bin/rspec
    - bin/rubocop

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 80
